services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=github_trending
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_trending"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=github_trending
      - PGUSER=postgres
      - PGPASSWORD=password
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SYNC_DATA_ON_STARTUP=false
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped

volumes:
  postgres_data: